In [2]:
import numpy as np

## 1D Array

In [3]:
oneDArray = np.array([1, 2, 3, 4])
print(oneDArray)

[1 2 3 4]


## 2D Array

In [4]:
twoDArray = np.array([[1,2,3,4],[4,5,6,7]])
print(twoDArray)


[[1 2 3 4]
 [4 5 6 7]]


### List Vs Numpy Array

In [ ]:
list =  [1,2,3,4] 
multList = list * 2 # double the items

In [ ]:
array = np.array([1, 2, 3, 4])
multArray = array * 2 # element wise multiplication, numpy is way much faster then list

In [ ]:
# arange = np.arange(1000) 
# print(arange)

## Creating array from scratch

In [ ]:
zeros = np.zeros((2,2)) # row and colum
print(zeros)

In [ ]:
ones = np.ones((2,2))
print(ones)

In [24]:
full = np.full((2,2),10)
print(full)

[[10 10]
 [10 10]]


In [25]:
random = np.random.random((2,2))
print(random)

[[0.83209749 0.86251688]
 [0.27312193 0.2628844 ]]


In [ ]:
sequence = np.arange(0,10,2)
print(sequence)

## Vector, Metrix, Tensor


In [ ]:
vector = np.array([1,2,3,4]) 
print(vector)

In [ ]:
matrix = np.array([[1,2],[3,4]])
print(matrix)

In [ ]:
tensor = np.array([[[1,2],[3,4]],
                  [[5,6],[7,8]]])
print(tensor)

## Array Proprties

In [5]:
arr = np.array([[1,2],[3,4]])

print(arr.shape) # Shape

(2, 2)


In [6]:
print(arr.ndim) # diamantions

2


In [7]:
print(arr.size) # size (no of elements)

4


In [8]:
print(arr.dtype)

int64


## Array Reshaping 

In [15]:
arr = np.arange(12)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [19]:
reshaped = arr.reshape((3,4)) # reshape
print(reshaped)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
flattened = reshaped.flatten() # flat
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
raveled = reshaped.ravel() # ravel (looks same as flat but it returns view/orignal insted of copy)
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
transposed =  reshaped.T
print(transposed)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
