In [6]:
import numpy as np
import matplotlib.pyplot as plt

# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==== Daraz sales nalysis ====")
print("\nShape:", sales_data.shape) # checking shape
print(sales_data[0]) # greeting first resturent data 
print(sales_data[:3]) # greeting first 3 resturent data



==== Daraz sales nalysis ====

Shape: (5, 5)
[     1 150000 180000 220000 250000]
[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]


In [8]:
# total sales per year
print(np.sum(sales_data, axis = 0))
# yearly total 
print(np.)

SyntaxError: invalid syntax (745753197.py, line 4)