In [29]:
import numpy 
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

## Indexcing and slicing 

In [8]:
array = numpy.array([1,2,3,4])
print(array[0]) #index
print(array[0:2]) # slice
print(array[0::2]) # step

1
[1 2]
[1 3]


In [17]:
array2D = numpy.array([[1,2],
                     [3,4]])
print(array2D[0,0]) # indexing in 2d array
print(array2D[0]) # accessing entire row
print(array2D[:,0]) # accessing entire column

1
[1 2]
[1 3]


## Sorting 

In [24]:
unsorted = numpy.array([1,9,8,5,4,2,7,10,20])
print(numpy.sort(unsorted)) # sort array 1D array
unsorted2D = numpy.array([[1,2],
                        [3,4]])
print(numpy.sort(unsorted2D, axis = 0)) # sort 2D array using axis

[ 1  2  4  5  7  8  9 10 20]
[[1 2]
 [3 4]]


## Filter

In [26]:
numbers = numpy.array([1,2,3,4,5,6,7,8])
evenNums = numbers[numbers % 2 == 0]
print(evenNums)


[2 4 6 8]


## Filter with mask

In [29]:
mask = numbers > 2
# mask is storing true,false
print(numbers[mask])

[3 4 5 6 7 8]


## Fancy indexing vs np.where()


In [32]:
indices = [1,2,3,4]
print(numbers[indices]) # fancy indexing 

whereResult = numpy.where(numbers > 2)  #where
# where is storing a array indices
print(numbers[whereResult])

[2 3 4 5]
[3 4 5 6 7 8]


## Conditions 

In [10]:
#condition_array = numpy.where(numbers > 5)

## Adding and Removing Data

In [13]:
arr1 = numpy.array([1,2,3,4])
arr2 = numpy.array([5,6,7,8])

combined = numpy.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6 7 8]


## Array compatibility


In [14]:
a = numpy.array([1,2])
b = numpy.array([3,4])
c = numpy.array([5,6])

print(a.shape == b.shape)

True


In [24]:
original = numpy.array([[1,2],[3,4]])

# row
new_row = numpy.array([[5,6]])
with_new_row = numpy.vstack((original, new_row))
print(with_new_row)

# column
new_col = numpy.array([[7],[8]])
with_new_col = numpy.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [28]:
arrr = numpy.array([1,2,3,4,5,6,7,8])
deleted = numpy.delete(arrr, 2)
print(deleted) # do not return a deleted value but a new updated array

Deleted value [1 2 4 5 6 7 8]
